# Generated by Django 4.2.4 on 2023-12-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ban",
            fields=[
                (
                    "work_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("author_id", models.JSONField()),
            ],
        ),
    ]
