# Generated by Django 4.2.8 on 2023-12-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanCount",
            fields=[
                (
                    "author_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ban_count", models.IntegerField(default=1)),
            ],
        ),
    ]
