# Generated by Django 3.1.3 on 2023-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('include', models.TextField(default='')),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
