# Generated by Django 3.2 on 2023-11-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('scholar_id', models.CharField(default='', max_length=128)),
                ('organization', models.CharField(default='', max_length=128)),
                ('introduction', models.TextField(default='', max_length=128)),
                ('real_name', models.CharField(default='', max_length=128)),
                ('user_degree', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
