# Generated by Django 3.2 on 2023-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.CharField(default='', max_length=128)),
                ('scholar_name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='cite_count',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='star',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='star',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='star',
            name='time',
            field=models.CharField(default='', max_length=128),
        ),
    ]
