# Generated by Django 3.2 on 2023-12-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231221_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
