# Generated by Django 3.2 on 2023-12-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_history_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
