# Generated by Django 3.2 on 2023-12-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_concern_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articleauthor',
            table='article_author',
        ),
    ]
