# Generated by Django 3.2 on 2023-11-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='0')),
                ('scholar_id', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('content', models.TextField(default='')),
                ('time', models.DateTimeField(default='')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scholar_apply',
            },
        ),
    ]
