# Generated by Django 3.2 on 2023-12-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ins_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='scholar_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='application',
            name='user_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
